import { writeFileSync, readFileSync, existsSync } from 'fs';
import { join } from 'path';
import hre from 'hardhat';

const TREASURY_ADDRESS = '0x1630C69E6dDA942AAE2E9182A69eF4dEC6ce0A9D';
const APP_URL = 'https://my-mystic-crate.vercel.app';

function variantMetadataUri(id: number) {
  return `${APP_URL}/metadata/variants/${id}.json`;
}

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  if (!deployer) {
    throw new Error('Set DEPLOYER_PRIVATE_KEY in .env.local (wallet needs Base ETH for gas).');
  }

  console.log('Deploying with:', deployer.address);
  console.log('Treasury:', TREASURY_ADDRESS);

  const collectionUri = `${APP_URL}/metadata/collection.json`;
  const MysticCrateNFT = await hre.ethers.getContractFactory('MysticCrateNFT');
  const contract = await MysticCrateNFT.deploy(TREASURY_ADDRESS, collectionUri);
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log('MysticCrateNFT deployed to:', address);

  const uris = Array.from({ length: 20 }, (_, i) => variantMetadataUri(i));
  const tx = await contract.setVariantURIs(uris as [string, ...string[]]);
  await tx.wait();
  console.log('Variant URIs configured (20 variants)');

  const deployedPath = join(process.cwd(), 'lib', 'deployed-address.ts');
  writeFileSync(
    deployedPath,
    `/** Auto-generated by deploy — Mystic Crate on Base mainnet */\nexport const DEPLOYED_NFT_CONTRACT = '${address}' as const;\n`,
  );
  console.log('Updated lib/deployed-address.ts');

  const envPath = join(process.cwd(), '.env.local');
  const envLine = `NEXT_PUBLIC_NFT_CONTRACT_ADDRESS=${address}\n`;
  if (existsSync(envPath)) {
    const prev = readFileSync(envPath, 'utf8');
    const without = prev
      .split('\n')
      .filter((l) => !l.startsWith('NEXT_PUBLIC_NFT_CONTRACT_ADDRESS='))
      .join('\n');
    writeFileSync(envPath, without.trimEnd() + '\n' + envLine);
  } else {
    writeFileSync(envPath, envLine);
  }
  console.log('Updated .env.local');

  console.log('\nOpenSea (after indexer sync):');
  console.log(`https://opensea.io/assets/base/${address}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
